# docker-compose.yml
version: '3.8'

services:
  backend:
    build:
      context: ./agents
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_PATH=/app/data/healthcare_data.db
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./data:/app/data
      - ./agents:/app
    networks:
      - healthcare-network
    restart: unless-stopped
    depends_on:
      data-generator:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - healthcare-network
    restart: unless-stopped

  data-generator:
    build:
      context: ./data
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
    command: python generate_dataset.py
    networks:
      - healthcare-network

networks:
  healthcare-network:
    driver: bridge

volumes:
  healthcare-data:
    driver: local