version: '3.8'

services:
  data-generator:
    build:
      context: ./data
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
    networks:
      - healthcare-network

  backend:
    build:
      context: ./agents
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_PATH=/data/healthcare_data.db
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    env_file:
      - .env
    volumes:
      - ./data:/data        # maps your data folder to /data inside container
      - ./agents:/app
    networks:
      - healthcare-network
    restart: unless-stopped
    depends_on:
      - data-generator
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - healthcare-network
    restart: unless-stopped

networks:
  healthcare-network:
    driver: bridge
